import { useState } from "react";
import useUserStore from "../store/userStore.js";
import { useComments, useCreateComment, useDeleteComment, useUpdateComment } from "../hooks/useComments.js";

export default function Comments({ boardId }) {
  const user = useUserStore((s) => s.user); const { data: comments = [], isLoading } = useComments(boardId); const create = useCreateComment(); const update = useUpdateComment(); const remove = useDeleteComment(); const [content, setContent] = useState(""); const [editing, setEditing] = useState(null); const [error, setError] = useState("");
  const submit = (event) => { event.preventDefault(); if (!content.trim()) return; create.mutate({ boardId, content: content.trim() }, { onSuccess: () => setContent(""), onError: (e) => setError(e.response?.data?.message ?? "댓글 등록에 실패했습니다.") }); };
  const canManage = (comment) => user?.username === comment.writer || user?.roles?.includes("ADMIN");
  return <section className="comments"><p className="kicker">COMMENTS · {comments.length}</p><h2>함께 나누는 이야기</h2>{user ? <form className="comment-form" onSubmit={submit}><textarea value={content} onChange={(e) => { setContent(e.target.value); setError(""); }} placeholder="댓글을 남겨 주세요" rows="3" /><button className="button button-primary" disabled={create.isPending}>{create.isPending ? "등록 중…" : "댓글 등록"}</button>{error && <p className="form-error">{error}</p>}</form> : <p className="comment-login">댓글 작성은 로그인 후 이용할 수 있습니다.</p>}{isLoading ? <p className="profile-state">댓글을 불러오는 중…</p> : <div className="comment-list">{comments.map((comment) => <article className="comment" key={comment.id}>{editing?.id === comment.id ? <CommentEditor comment={comment} pending={update.isPending} onCancel={() => setEditing(null)} onSave={(value) => update.mutate({ boardId, commentId: comment.id, content: value }, { onSuccess: () => setEditing(null) })} /> : <><header><strong>{comment.writer}</strong><span>{comment.createdAt?.slice(0, 10)}</span></header><p>{comment.content}</p>{canManage(comment) && <div className="comment-actions"><button onClick={() => setEditing(comment)}>수정</button><button onClick={() => remove.mutate({ boardId, commentId: comment.id })}>삭제</button></div>}</>}</article>)}{!comments.length && <p className="profile-state">첫 번째 댓글을 남겨 보세요.</p>}</div>}</section>;
}
function CommentEditor({ comment, pending, onCancel, onSave }) { const [value, setValue] = useState(comment.content); return <form className="comment-edit" onSubmit={(e) => { e.preventDefault(); onSave(value); }}><textarea value={value} onChange={(e) => setValue(e.target.value)} rows="3" /><button className="button button-primary" disabled={pending}>저장</button><button type="button" className="button button-ghost" onClick={onCancel}>취소</button></form>; }
