import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useBoard, useCreateBoard, useUpdateBoard } from "../hooks/useBoard.js";
import useFeedbackStore from "../store/feedbackStore.js";

export default function BoardFormV2() {
  const { id } = useParams(); const editing = Boolean(id); const { data: board, isLoading } = useBoard(id); const create = useCreateBoard(); const update = useUpdateBoard(); const navigate = useNavigate(); const showToast = useFeedbackStore((s) => s.showToast);
  if (editing && isLoading) return <div className="state-card page-state">게시글을 불러오는 중입니다.</div>;
  return <Editor key={id ?? "new"} initial={board ?? { title: "", content: "" }} editing={editing} pending={create.isPending || update.isPending} onSubmit={(form) => { const options = { onSuccess: () => { showToast(editing ? "게시글을 수정했습니다." : "새 게시글을 등록했습니다."); navigate(editing ? `/boards/${id}` : "/boards"); }, onError: (e) => showToast(e.response?.data?.message ?? "요청을 처리하지 못했습니다.", "error") }; editing ? update.mutate({ id, boardData: form }, options) : create.mutate(form, options); }} />;
}
function Editor({ initial, editing, pending, onSubmit }) { const [form, setForm] = useState({ title: initial.title, content: initial.content }); const [error, setError] = useState(""); const change = (e) => setForm((old) => ({ ...old, [e.target.name]: e.target.value })); const submit = (e) => { e.preventDefault(); if (!form.title.trim() || !form.content.trim()) return setError("제목과 내용을 모두 입력해 주세요."); onSubmit({ title: form.title.trim(), content: form.content.trim() }); }; return <section className="editor-card"><p className="kicker">{editing ? "REFINE YOUR THOUGHT" : "START A DISCUSSION"}</p><h1>{editing ? "생각을 다듬어 보세요" : "무슨 생각을 하고 있나요?"}</h1><p className="editor-intro">작성자는 현재 로그인한 계정으로 자동 설정됩니다.</p><form onSubmit={submit}><label>제목<input required name="title" maxLength="200" value={form.title} onChange={change} placeholder="이야기의 제목을 적어 주세요" /></label><label>내용<textarea required name="content" rows="10" value={form.content} onChange={change} placeholder="자유롭게 이야기를 들려주세요" /></label>{error && <p className="form-error">{error}</p>}<div className="form-actions"><button className="button button-primary" disabled={pending}>{pending ? "저장 중…" : editing ? "수정 완료" : "글 등록하기"}</button><Link className="button button-ghost" to={editing ? `/boards/${initial.id}` : "/boards"}>취소</Link></div></form></section>; }
