import { useDeferredValue, useState } from 'react'
import { Link } from 'react-router-dom'
import { useBoards } from '../hooks/useBoard.js'

export default function BoardList() {
  const [keyword, setKeyword] = useState(''); const [page, setPage] = useState(0); const deferredKeyword = useDeferredValue(keyword)
  const { data, isLoading, isFetching, isError, error } = useBoards({ page, size: 8, keyword: deferredKeyword })
  const search = (event) => { setKeyword(event.target.value); setPage(0) }
  return <div className="surface p-3 p-md-4"><div className="d-flex flex-wrap gap-3 justify-content-between align-items-end mb-4"><div><p className="eyebrow mb-1">Community</p><h1 className="page-title">게시글</h1></div><Link className="btn btn-primary" to="/boards/write">새 글 작성</Link></div><div className="position-relative mb-3"><input className="form-control" value={keyword} onChange={search} placeholder="제목으로 검색" aria-label="게시글 검색" />{isFetching && <span className="position-absolute end-0 top-50 translate-middle-y me-3 small text-secondary">검색 중</span>}</div>{isError ? <div className="alert alert-danger mb-0">목록을 불러오지 못했습니다: {error.message}</div> : <><div className="table-responsive"><table className="table table-hover mb-0"><thead><tr className="small text-secondary"><th>번호</th><th>제목</th><th>작성자</th><th>조회</th><th>등록일</th></tr></thead><tbody>{isLoading ? <tr><td colSpan="5" className="text-center py-5 text-secondary">게시글을 불러오는 중입니다…</td></tr> : data.content.length ? data.content.map((board) => <tr key={board.id}><td className="text-secondary">{board.id}</td><td><Link className="board-title" to={`/boards/${board.id}`}>{board.title}</Link></td><td>{board.writer}</td><td>{board.viewCount}</td><td className="text-secondary">{board.createdAt?.slice(0, 10)}</td></tr>) : <tr><td colSpan="5" className="text-center py-5 text-secondary">검색 결과가 없습니다.</td></tr>}</tbody></table></div><nav className="d-flex justify-content-center gap-2 mt-4" aria-label="페이지 이동"><button className="btn btn-outline-secondary btn-sm" disabled={page === 0} onClick={() => setPage((value) => value - 1)}>이전</button><span className="align-self-center small text-secondary">{page + 1} / {data?.totalPages ?? 1}</span><button className="btn btn-outline-secondary btn-sm" disabled={!data || page + 1 >= data.totalPages} onClick={() => setPage((value) => value + 1)}>다음</button></nav></>}</div>
}
